# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import functools
import os
import re

from absl.testing import absltest
from absl.testing import parameterized
import hypothesis as hp
from jax._src import hypothesis_test_util as htu
from jax._src import test_util as jtu

htu.setup_hypothesis()


shard_index = int(os.environ.get("TEST_SHARD_INDEX", "0"))
total_shards = int(os.environ.get("TEST_TOTAL_SHARDS", "1"))


@jtu.skip_under_pytest("The test sharding runner is bazel-specific")
class HypothesisTest(htu.HypothesisShardedTestCase):
  """Tests that Hypothesis tests and standard tests are sharded correctly."""

  _hyp_calls = []
  _all_generated_x = []

  @classmethod
  def setUpClass(cls):
    super().setUpClass()
    # Intercept inner_test to track all candidates generated by hypothesis
    hyp_handle = cls.test_hyp.hypothesis
    current_inner = hyp_handle.inner_test

    # We must use the exact original inner test when testing our shard hashes.
    # current_inner is the wrapper applied by HypothesisShardedTestCase, so
    # its __wrapped__ is the raw inner test function (if sharded).
    cls._original_inner_test = getattr(current_inner, "__wrapped__", current_inner)

    @functools.wraps(current_inner)
    def tracking_wrapper(*args, **kwargs):
      x_val = kwargs.get("x")
      if x_val is None and len(args) > 1:
        x_val = args[1]
      cls._all_generated_x.append(x_val)
      return current_inner(*args, **kwargs)

    hyp_handle.inner_test = tracking_wrapper

  @hp.given(x=hp.strategies.integers(min_value=0, max_value=10000))
  @hp.settings(
      max_examples=100,
      suppress_health_check=[hp.HealthCheck.too_slow],
      database=None,
  )
  def test_hyp(self, x):
    # This hypothesis test is subject to inner-sharding and will run iterations
    # distributed across shards. We track the examples that this shard actually
    # executes.
    type(self)._hyp_calls.append(x)

  def test_m_std_a(self):
    # We expect non-hypothesis tests to be assigned to shards round-robin.
    self.assertEqual(shard_index, 0)

  def test_m_std_b(self):
    self.assertEqual(shard_index, 1 % total_shards)

  def test_m_std_c(self):
    self.assertEqual(shard_index, 2 % total_shards)

  @classmethod
  def tearDownClass(cls):
    # Check that the current shard evaluated exactly the subset of candidates
    # it should have.
    test_instance = cls("test_hyp")

    expected_calls = set()
    for x in cls._all_generated_x:
      shard = htu.hypothesis_inner_test_shard(
          cls._original_inner_test, (test_instance,), {"x": x}, total_shards
      )
      if shard == shard_index:
        expected_calls.add(x)

    actual_calls = set(cls._hyp_calls)
    assert actual_calls == expected_calls, (
        "Mismatch between expected executions and actual executions on shard"
        f" {shard_index}!\nMissing: {expected_calls - actual_calls}\nExtra:"
        f" {actual_calls - expected_calls}"
    )

    super().tearDownClass()


@jtu.skip_under_pytest("The test sharding runner doesn't run under pytest")
class SingleShardTest(jtu.JaxTestCase):
  # Standard test cases should be assigned to shard round-robin.

  def test_z_absl_std1(self):
    self.assertEqual(shard_index, 0)

  def test_z_absl_std2(self):
    self.assertEqual(shard_index, 1 % total_shards)

  def test_z_absl_std3(self):
    self.assertEqual(shard_index, 2 % total_shards)


# Avoid differing_executors if we run on unsharded environment.
_helper_fail_suppressed_checks = [hp.HealthCheck.too_slow]
if hasattr(hp.HealthCheck, "differing_executors"):
  _helper_fail_suppressed_checks.append(hp.HealthCheck.differing_executors)


# Verify that shrinking to minimal example still works when sharding.
class HypothesisShrinkTest(htu.HypothesisShardedTestCase):

  @hp.given(x=hp.strategies.integers(min_value=0, max_value=10000))
  @hp.settings(
      max_examples=100,
      suppress_health_check=_helper_fail_suppressed_checks,
      database=None,
  )
  def helper_fail(self, x):
    self.assertLess(x, 10)

  @classmethod
  def setUpClass(cls):
    super().setUpClass()
    # Manually apply the sharding wrapper to helper_fail
    handle = cls.helper_fail.hypothesis
    handle.inner_test = htu._shard_aware_hypothesis_inner_test(
        handle.inner_test
    )

  # Run 2 instances of the test so that it runs on both shards and can verify
  # that hypothesis shrinking finds the right value (10) on both.
  @parameterized.parameters(0, 1)
  def test_meta_shrink(self, unused_id):
    try:
      self.helper_fail()
    except AssertionError as e:
      notes = getattr(e, "__notes__", [])
      self.assertTrue(
          any(re.search(r"\bx=10\b", note) for note in notes),
          f"Exact match for 'x=10' not found in exception notes: {notes}",
      )
      return
    self.fail("helper_fail did not raise AssertionError")


if __name__ == "__main__":
  absltest.main(testLoader=htu.HypothesisShardedTestLoader())
