# Copyright 2025 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###
### The following are test boilerplate
###
from absl.testing import absltest
import jax
from jax._src import test_util as jtu


jax.config.parse_flags_with_absl()

### Copy here the contents of the repro.py file, except the call to `fun_main`


# This file was generated by JAX repro extractor.

from jax._src import config

if config.enable_x64.value != False:
  raise ValueError("This repro was saved with JAX_ENABLE_X64=False."
                   "You should run with with the same value of the flag.")


### Copy here the repro.py output, except the last line


class RunReproAsTest(jtu.JaxTestCase):

  @jtu.run_on_devices("cpu",)
  def test_main(self):
    ### Add here the last line of the repro.py
    # _repro_result = fun_main_0()
    pass

if __name__ == "__main__":
  absltest.main(testLoader=jtu.JaxTestLoader())
