# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

def register_xla_transform(name: str, stage: int, callback: object) -> None: ...
def clear_xla_transform(name: str, stage: int) -> bool: ...
def register_xla_transform_c_api(
    client: object, name: str, stage: int, callback: object
) -> None: ...
def register_xla_transform_c_api_by_plugin(
    plugin_name: str, name: str, stage: int, callback: object
) -> None: ...
def clear_xla_transform_c_api(
    client: object, name: str, stage: int
) -> bool: ...
