# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections.abc import Iterable
from typing import Any

def safe_map(*args, **kwargs) -> Any: ...
def foreach(*args, **kwargs) -> Any:
  """foreach() applies a function elementwise to one or more iterables, ignoring the return values and returns None.

  The iterables must all have the same lengths.
  """

def safe_zip(*args, **kwargs) -> Any: ...
def topological_sort(parents_attr: str, end_nodes: Iterable) -> list:
  """Computes a topological sort of a graph of objects.

  parents_attr is the name of the attribute on each object that contains the
  list of parent objects. end_nodes is an iterable of objects from which we
  should start a backwards search.
  """

def absl_set_min_log_level(arg: int, /) -> None: ...
def absl_set_vlog_level(arg0: str, arg1: int, /) -> int: ...
def absl_set_global_vlog_level(arg: int, /) -> int: ...
def absl_set_stderr_threshold(arg: int, /) -> None: ...

class Mutex:
  def __init__(self) -> None: ...
  def lock(self) -> None: ...
  def unlock(self) -> None: ...
  def assert_held(self) -> None: ...
  def reader_lock(self) -> None: ...
  def reader_unlock(self) -> None: ...
  def assert_reader_held(self) -> None: ...
  def writer_lock(self) -> None: ...
  def writer_unlock(self) -> None: ...

def install_failure_signal_handler(
    call_previous_handler: bool = ...,
) -> None: ...
