# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

"""Config library"""

unset: object = ...

class Config[T]:
  def __init__(
      self,
      name: str,
      value: T,
      *,
      include_in_jit_key: bool = ...,
      include_in_trace_context: bool = ...,
  ) -> None: ...
  @property
  def value(self) -> T: ...
  @property
  def name(self) -> str: ...
  def get_local(self) -> T: ...
  def get_global(self) -> T: ...
  def set_local(self, value: T) -> None: ...
  def swap_local(self, value: T) -> T: ...
  def set_global(self, value: T) -> None: ...

def trace_context() -> tuple: ...
def trace_context_names() -> tuple: ...
