# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# INTEL ONEAPI plugin extension and GPU kernels
load("@local_config_sycl//sycl:build_defs.bzl", "sycl_library")
load("@rules_python//python:defs.bzl", "py_library")
load(
    "//jaxlib:jax.bzl",
    "nanobind_extension",
)

licenses(["notice"])

package(
    default_applicable_licenses = [],
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "oneapi_gpu_runtime_hdrs",
    hdrs = ["oneapi_gpu_runtime.h"],
    deps = [
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@local_config_sycl//sycl:sycl_headers",
    ],
)

cc_library(
    name = "oneapi_gpu_runtime",
    srcs = ["oneapi_gpu_runtime.cc"],
    hdrs = ["oneapi_gpu_runtime.h"],
    copts = ["-fsycl"],
    features = ["-use_header_modules"],
    linkopts = ["-fsycl"],
    deps = [
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@local_config_sycl//sycl:sycl_headers",
    ],
)

cc_library(
    name = "oneapi_vendor",
    defines = ["JAX_GPU_ONEAPI=1"],
    textual_hdrs = [
        "//jaxlib/gpu:vendor.h",
    ],
    deps = [
        ":oneapi_gpu_runtime_hdrs",
    ],
)

cc_library(
    name = "oneapi_gpu_kernel_helpers",
    hdrs = ["//jaxlib/gpu:gpu_kernel_helpers.h"],
    features = ["-use_header_modules"],
    deps = [
        ":oneapi_vendor",
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings:str_format",
    ],
)

sycl_library(
    name = "oneapisolver_kernels_ffi",
    srcs = ["oneapi_solver_kernels_ffi.cc"],
    hdrs = ["//jaxlib/gpu:solver_kernels_ffi.h"],
    features = ["-use_header_modules"],
    deps = [
        ":oneapi_gpu_kernel_helpers",
        ":oneapi_gpu_runtime",
        ":oneapi_vendor",
        "//jaxlib:ffi_helpers",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:str_format",
        "@xla//xla/ffi/api:ffi",
    ],
)

nanobind_extension(
    name = "_solver",
    srcs = ["//jaxlib/gpu:solver.cc"],
    copts = [
        "-fexceptions",
        "-fno-strict-aliasing",
    ],
    features = ["-use_header_modules"],
    module_name = "_solver",
    deps = [
        ":oneapi_gpu_kernel_helpers",
        ":oneapi_vendor",
        ":oneapisolver_kernels_ffi",
        "//jaxlib:kernel_nanobind_helpers",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:str_format",
        "@oneapi//:headers",
        "@nanobind",
        "@xla//xla/tsl/python/lib/core:numpy",
    ],
)

py_library(
    name = "oneapi_gpu_support",
    deps = [
        ":_solver",
    ],
)

sycl_library(
    name = "py_client_gpu",
    srcs = ["//jaxlib/gpu:py_client_gpu.cc"],
    hdrs = ["//jaxlib/gpu:py_client_gpu.h"],
    copts = [
        "-fexceptions",
        "-fno-strict-aliasing",
    ],
    features = ["-use_header_modules"],
    deps = [
        ":oneapi_gpu_kernel_helpers",
        ":oneapi_gpu_runtime",
        ":oneapi_vendor",
        "//jaxlib:ffi",
        "@com_google_absl//absl/algorithm:container",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/container:inlined_vector",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "@dlpack",
        "@nanobind",
        "@xla//third_party/python_runtime:headers",  # buildcleaner: keep
        "@xla//xla:comparison_util",
        "@xla//xla:shape_util",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/ffi:ffi_api",
        "@xla//xla/ffi/api:ffi",
        "@xla//xla/pjrt:host_callback",
        "@xla//xla/pjrt:transpose",
        "@xla//xla/python:nb_numpy",
        "@xla//xla/python:types",
        "@xla//xla/service:platform_util",
    ],
)

nanobind_extension(
    name = "oneapi_plugin_extension",
    srcs = ["oneapi_plugin_extension.cc"],
    module_name = "oneapi_plugin_extension",
    deps = [
        ":py_client_gpu",
        "//jaxlib:kernel_nanobind_helpers",
        "//jaxlib/gpu:gpu_plugin_extension",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/strings",
        "@oneapi//:headers",
        "@nanobind",
    ],
)
