# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

def cuda_runtime_build_version() -> int: ...
def cudnn_build_version() -> int: ...
def cublas_build_version() -> int: ...
def cupti_build_version() -> int: ...
def cufft_build_version() -> int: ...
def cusolver_build_version() -> int: ...
def cusparse_build_version() -> int: ...
def cuda_runtime_get_version() -> int: ...
def cuda_driver_get_version() -> int: ...
def cudnn_get_version() -> int: ...
def cupti_get_version() -> int: ...
def cufft_get_version() -> int: ...
def cusolver_get_version() -> int: ...
def cublas_get_version() -> int: ...
def cusparse_get_version() -> int: ...
def cuda_compute_capability(arg: int, /) -> int: ...
def cuda_supports_multicast(arg: int, /) -> bool: ...
def cuda_device_count() -> int: ...
