# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

import types

def register_custom_call_target(
    c_api: types.CapsuleType,
    fn_name: object,
    fn: object,
    xla_platform_name: str,
    api_version: int = ...,
    traits: int = ...,
) -> None: ...
def register_custom_type(
    c_api: types.CapsuleType, type_name: str, type_id: object
) -> None: ...
def ffi_types() -> dict: ...
def ffi_handlers() -> dict: ...
def get_device_ordinal(data_value: int) -> int: ...
