#!/bin/bash

# Copyright 2022 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x

echo "GITHUB_WORKSPACE_REMOTE=${GITHUB_WORKSPACE_REMOTE}"
TEST_NAME="e2e-t5x"

# File system and volume glue code
#-------------------------------------------------------------------------------
CONTAINER="docker://nvcr.io#nvidia/tensorflow:22.11-tf2-py3"
CONTAINER_NAME="multinode_ci_test_container_${TEST_NAME}_$RANDOM"

# create run specific output directory for ease of analysis
BASE_OUTPUT_DIR="${GITHUB_WORKSPACE_REMOTE}/outputs/"
OUTFILE="${BASE_OUTPUT_DIR}/output-test-${TEST_NAME}-%J-%n-%t.txt"
mkdir -p "$BASE_OUTPUT_DIR"

# Default env variables for paths required by t5x training scripts
OUTPUT_DIR=/outputs
E2E_TESTS_WORKSPACE_DIR=/localdir/e2e_tests_workspace
T5X_DIR="${E2E_TESTS_WORKSPACE_DIR}/t5x"
TFDS_DATA_DIR="${E2E_TESTS_WORKSPACE_DIR}/datasets"

MOUNTS="--container-mounts=$BASE_OUTPUT_DIR:$OUTPUT_DIR"
EXPORTS="--export=ALL,PYTHONPATH=${T5X_DIR}"
#-------------------------------------------------------------------------------

# Setup command to be run before the actual test command
# We remove cudf from the container as a temporary WAR to a protobuf
# dependency issue between cudf and tensorflow-cpu that t5x try to
# install.
read -r -d '' setup_cmd <<EOF
rm -rf ${E2E_TESTS_WORKSPACE_DIR}/* \
&& mkdir -p ${E2E_TESTS_WORKSPACE_DIR} \
&& mkdir -p ${TFDS_DATA_DIR} \
&& python3.8 -m pip install git+https://github.com/google/jax \
&& python3.8 -m pip install jaxlib --pre -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_cuda_releases.html \
&& git clone https://github.com/google-research/t5x.git ${T5X_DIR} \
&& python3.8 -m pip uninstall -y cudf dask-cudf \
&& python3.8 -m pip install ${T5X_DIR} \
&& python3.8 -m pip install ${T5X_DIR}/t5x/contrib/gpu/scripts_gpu/dummy_wikipedia_config \
&& python3.8 -m pip install -U git+https://github.com/google-research/jestimator \
&& hostname > ${E2E_TESTS_WORKSPACE_DIR}/hostname.txt
EOF

# Main pytest command that runs the tests
read -r -d '' cmd <<EOF
date \
&& python3.8 -m pip list | grep jax \
&& python3.8 ${T5X_DIR}/t5x/train.py \
        --gin_file="${T5X_DIR}/t5x/contrib/gpu/scripts_gpu/dummy_wikipedia_config/small_pretrain_dummy_wikipedia.gin" \
        --gin.MODEL_DIR=\"${OUTPUT_DIR}/model_dir\" \
        --gin.network.T5Config.dtype=\"bfloat16\"  \
        --gin.TRAIN_STEPS=100 \
        --gin.CheckpointConfig.save=None \
        --multiprocess_gpu
EOF

# Count errors
errors=0 && trap errors=1 ERR

# Run any setup commands before the actual test command to make sure
# that the processes are launched together
echo "$setup_cmd"
srun -o "$OUTFILE" -e "$OUTFILE" \
    -t 00:10:00 \
    --ntasks-per-node=1 \
    --container-writable \
    --container-image="$CONTAINER" \
    --container-name="$CONTAINER_NAME" \
    "$MOUNTS"  \
    "$EXPORTS" \
    timeout -v -k 0.5m 9m bash -c "${setup_cmd}"

# Run the actual test command
echo "$cmd"
srun -o "$OUTFILE" -e "$OUTFILE" \
    -t 00:15:00 \
    --ntasks-per-node=8 \
    --open-mode=append \
    --container-writable \
    --container-image="$CONTAINER" \
    --container-name="$CONTAINER_NAME" \
    "$MOUNTS"  \
    "$EXPORTS" \
    timeout -v -k 0.5m 14m bash -c "${cmd}"

test $errors = 0
