# Copyright 2026 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

from collections.abc import Sequence
from mlir import ir

def register_dialect(context: ir.Context, load: bool = ...) -> None: ...
def register_inliner_extensions(arg: ir.Context, /) -> None: ...

class BarrierType(ir.Type):
  @staticmethod
  def isinstance(other_type: ir.Type) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      orders_tensor_core: bool = False, context: ir.Context | None = None
  ) -> BarrierType:
    """Creates a BarrierType."""

  @property
  def orders_tensor_core(self) -> bool: ...

class TileTransformAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      tiling: Sequence[int], context: ir.Context | None = None
  ) -> TileTransformAttr:
    """Creates a TileTransformAttr with the given tiling."""

  @property
  def tiling(self) -> ir.DenseI32ArrayAttr: ...

class TransposeTransformAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      permutation: Sequence[int], context: ir.Context | None = None
  ) -> TransposeTransformAttr:
    """Creates a TransposeTransformAttr with the given permutation."""

  @property
  def permutation(self) -> ir.DenseI32ArrayAttr: ...

class SwizzleTransformAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      swizzle: int, context: ir.Context | None = None
  ) -> SwizzleTransformAttr:
    """Creates a SwizzleTransformAttr with the given swizzle."""

  @property
  def swizzle(self) -> int: ...

class WGSplatFragLayoutAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      shape: ir.DenseI64ArrayAttr, context: ir.Context | None = None
  ) -> WGSplatFragLayoutAttr:
    """Creates a WGSplatFragLayoutAttr with the given shape."""

  @property
  def shape(self) -> ir.DenseI64ArrayAttr: ...

class WGStridedFragLayoutAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      shape: ir.DenseI64ArrayAttr,
      vector_size: int,
      context: ir.Context | None = None,
  ) -> WGStridedFragLayoutAttr:
    """Creates a WGStridedFragLayoutAttr."""

  @property
  def shape(self) -> ir.DenseI64ArrayAttr: ...
  @property
  def vector_size(self) -> int: ...

class ReplicatedAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(times: int, context: ir.Context | None = None) -> ReplicatedAttr:
    """Creates a ReplicatedAttr."""

  @property
  def times(self) -> int: ...

class TiledLayoutAttr(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(
      tiling: ir.ArrayAttr,
      warp_dims: ir.ArrayAttr,
      lane_dims: ir.ArrayAttr,
      vector_dim: int,
      context: ir.Context | None = None,
  ) -> TiledLayoutAttr:
    """Creates a TiledLayoutAttr."""

  @property
  def tiling(self) -> ir.ArrayAttr: ...
  @property
  def warp_dims(self) -> ir.ArrayAttr: ...
  @property
  def lane_dims(self) -> ir.ArrayAttr: ...
  @property
  def vector_dim(self) -> int: ...

class CopyPartitionAttrInterface(ir.Attribute):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...

class CopyReplicatedAttr(CopyPartitionAttrInterface):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(context: ir.Context | None = None) -> CopyReplicatedAttr:
    """Creates a CopyReplicatedAttr."""

class CopyPartitionedAttr(CopyPartitionAttrInterface):
  @staticmethod
  def isinstance(other_attribute: ir.Attribute) -> bool: ...
  def __repr__(self) -> str: ...
  @staticmethod
  def get_static_typeid() -> ir.TypeID: ...
  @staticmethod
  def get(axis: int, context: ir.Context | None = None) -> CopyPartitionedAttr:
    """Creates a CopyPartitionedAttr."""

  @property
  def axis(self) -> int: ...
