from typing import Any

class ProfilerServer: ...
def start_server(port: int) -> ProfilerServer: ...

def register_plugin_profiler(c_api: Any) -> None: ...

def get_profiled_instructions_proto(tensorboard_dir: str) -> bytes: ...
def get_instructions_profile(tensorboard_dir: str) -> list[tuple[str, float]]: ...
def get_fdo_profile(
    xspace: bytes, as_textproto: bool = ...
) -> bytes | str: ...

class ProfilerSession:
  def __init__(self, options: ProfileOptions | None = ...) -> None: ...
  def stop(self) -> bytes: ...
  def stop_and_export(self, tensorboard_dir: str) -> None: ...
  def export(self, xspace: bytes, tensorboard_dir: str) -> None:...

class ProfileOptions:
  include_dataset_ops: bool
  host_tracer_level: int
  python_tracer_level: int
  enable_hlo_proto: bool
  start_timestamp_ns: int
  duration_ms: int
  repository_path: str
  raise_error_on_start_failure: bool
  advanced_configuration: dict[str, Any]
  session_id: str

def aggregate_profiled_instructions(profiles: list[bytes], percentile: int) -> str: ...

class TraceMe:
  def __init__(self, name: str, **kwargs: Any) -> None: ...
  def __enter__(self) -> TraceMe: ...
  def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
  def set_metadata(self, **kwargs: Any) -> None: ...
  @staticmethod
  def is_enabled() -> bool: ...

def set_metadata(key: str, value: str) -> None: ...
def clear_metadata() -> None: ...
