# Copyright 2023 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Note: import <name> as <name> is required for names to be exported.
# See PEP 484 & https://github.com/google/jax/issues/7570

from jax._src.interpreters.batching import (
  Array as Array,
  AxisSize as AxisSize,
  BatchTrace as BatchTrace,
  BatchTracer as BatchTracer,
  BatchingRule as BatchingRule,
  ConcatAxis as ConcatAxis,
  Elt as Elt,
  FromEltHandler as FromEltHandler,
  GetIdx as GetIdx,
  IndexedAxisSize as IndexedAxisSize,
  MakeIotaHandler as MakeIotaHandler,
  MapSpec as MapSpec,
  NotMapped as NotMapped,
  Pile as Pile,
  PileAxis as PileAxis,
  PileTy as PileTy,
  ToEltHandler as ToEltHandler,
  Trace as Trace,
  Tracer as Tracer,
  Vmappable as Vmappable,
  Zero as Zero,
  ZeroIfMapped as ZeroIfMapped,
  _batch_inner as _batch_inner,
  _batch_jaxpr as _batch_jaxpr,
  _batch_jaxpr2 as _batch_jaxpr2,
  _batch_jaxpr_axes as _batch_jaxpr_axes,
  _batch_jaxpr_inner as _batch_jaxpr_inner,
  _batch_jaxpr_outer as _batch_jaxpr_outer,
  _batch_outer as _batch_outer,
  _handle_scalar_broadcasting as _handle_scalar_broadcasting,
  _main_trace_for_axis_names as _main_trace_for_axis_names,
  _match_axes_and_sum as _match_axes_and_sum,
  _match_axes_jaxpr as _match_axes_jaxpr,
  _matchaxis_symbolic_zeros as _matchaxis_symbolic_zeros,
  _merge_bdims as _merge_bdims,
  _pile_flatten as _pile_flatten,
  _pile_result as _pile_result,
  _pile_unflatten as _pile_unflatten,
  _update_annotation as _update_annotation,
  add_batched as add_batched,
  add_jaxvals as add_jaxvals,
  add_jaxvals_p as add_jaxvals_p,
  as_hashable_function as as_hashable_function,
  axis_primitive_batchers as axis_primitive_batchers,
  batch as batch,
  batch_custom_jvp_subtrace as batch_custom_jvp_subtrace,
  batch_custom_vjp_bwd as batch_custom_vjp_bwd,
  batch_jaxpr as batch_jaxpr,
  batch_jaxpr2 as batch_jaxpr2,
  batch_jaxpr_axes as batch_jaxpr_axes,
  batch_subtrace as batch_subtrace,
  bdim_at_front as bdim_at_front,
  broadcast as broadcast,
  broadcast_batcher as broadcast_batcher,
  canonicalize_axis as canonicalize_axis,
  collections as collections,
  config as config,
  core as core,
  curry as curry,
  dataclasses as dataclasses,
  defbroadcasting as defbroadcasting,
  defreducer as defreducer,
  defvectorized as defvectorized,
  flatten_fun_for_vmap as flatten_fun_for_vmap,
  from_elt as from_elt,
  from_elt_handlers as from_elt_handlers,
  is_vmappable as is_vmappable,
  lu as lu,
  make_iota as make_iota,
  make_iota_handlers as make_iota_handlers,
  map as map,
  matchaxis as matchaxis,
  memoize as memoize,
  moveaxis as moveaxis,
  not_mapped as not_mapped,
  np as np,
  partial as partial,
  pe as pe,
  pile_axis as pile_axis,
  primitive_batchers as primitive_batchers,
  raise_to_shaped as raise_to_shaped,
  reassemble_concat_axes as reassemble_concat_axes,
  reducer_batcher as reducer_batcher,
  register_pytree_node as register_pytree_node,
  register_vmappable as register_vmappable,
  safe_map as safe_map,
  safe_zip as safe_zip,
  segment_sum as segment_sum,
  source_info_util as source_info_util,
  spec_types as spec_types,
  split_list as split_list,
  spmd_axis_primitive_batchers as spmd_axis_primitive_batchers,
  to_elt as to_elt,
  to_elt_handlers as to_elt_handlers,
  tree_flatten as tree_flatten,
  tree_unflatten as tree_unflatten,
  unpack_concat_axes as unpack_concat_axes,
  unregister_vmappable as unregister_vmappable,
  unsafe_map as unsafe_map,
  unsafe_zip as unsafe_zip,
  unzip2 as unzip2,
  unzip3 as unzip3,
  vectorized_batcher as vectorized_batcher,
  vmappables as vmappables,
  vtile as vtile,
  weakref_lru_cache as weakref_lru_cache,
  zero_if_mapped as zero_if_mapped,
  zeros_like_batched as zeros_like_batched,
  zeros_like_jaxval as zeros_like_jaxval,
  zeros_like_p as zeros_like_p,
)
