name: CI - Address Sanitizer (nightly)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 12 * * *" # Daily at 12:00 UTC
  workflow_dispatch: # allows triggering the workflow run manually
  pull_request: # Automatically trigger on pull requests affecting this file
    branches:
      - main
    paths:
      - '**/workflows/asan.yaml'
permissions: {}

env:
  PYTHON_VERSION: "3.13"
  CPYTHON_URL: "https://storage.googleapis.com/ml-sysroot-testing/python/cpython-3.13.x-asan-shared-linux-x86_64-llvm-18.1.8.tar.gz"
  CPYTHON_SHA256: "cc7354abad5ab5b87aae3c870e510860c9ffefcd3d8f6c3e02129aaf9d30a5bb"
  CPYTHON_PREFIX: "cpython-3.13.x-asan-shared-linux-x86_64-llvm-18.1.8"
  UV_DEFAULT_INDEX: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"
  PIP_INDEX_URL: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"

jobs:
  asan:
    # Don't execute in fork due to runner type
    if: github.repository == 'jax-ml/jax'
    runs-on: linux-x86-n4-64
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: jax
          persist-credentials: false
      - name: Build JAX
        run: |
          cd jax
          python build/build.py build --wheels=jaxlib --verbose \
            --bazel_options=--color=yes \
            --bazel_options=--config=asan_shared \
            --python_version=${PYTHON_VERSION} \
            --bazel_options=--repo_env=HERMETIC_PYTHON_URL="${CPYTHON_URL}" \
            --bazel_options=--repo_env=HERMETIC_PYTHON_SHA256=${CPYTHON_SHA256} \
            --bazel_options=--repo_env=HERMETIC_PYTHON_PREFIX="${CPYTHON_PREFIX}/"

      - name: Run tests
        env:
          ASAN_OPTIONS: detect_leaks=0
          JAX_NUM_GENERATED_CASES: 1
          JAX_ENABLE_X64: true
          JAX_SKIP_SLOW_TESTS: true
          PY_COLORS: 1
        run: |
          echo "Download CPython with ASAN support"
          cd ${GITHUB_WORKSPACE}
          wget ${CPYTHON_URL}
          tar -xzf ${CPYTHON_PREFIX}.tar.gz

          echo "Install python requirements and JAX"
          ${GITHUB_WORKSPACE}/${CPYTHON_PREFIX}/bin/python3 -m venv \
            ${GITHUB_WORKSPACE}/${CPYTHON_PREFIX}/venv
          source ${GITHUB_WORKSPACE}/${CPYTHON_PREFIX}/venv/bin/activate
          pip install uv~=0.5.30
          cd jax
          uv pip install -r build/test-requirements.txt
          uv pip install dist/jaxlib-*.whl -e .

          echo "Run tests"
          echo "JAX_NUM_GENERATED_CASES=$JAX_NUM_GENERATED_CASES"
          echo "JAX_ENABLE_X64=$JAX_ENABLE_X64"
          echo "JAX_SKIP_SLOW_TESTS=$JAX_SKIP_SLOW_TESTS"
          python -m pytest -n 32 --tb=short --maxfail=20 tests
