# CI - Bazel ROCm tests
#
# This workflow runs the ROCm tests with Bazel. It can only be triggered by other workflows via
# `workflow_call`. It is used by the `CI - Bazel ROCm tests (RBE)`,`CI - Wheel Tests (Continuous)`
# and `CI - Wheel Tests (Nightly/Release)` workflows to run the Bazel ROCm tests.
#
# It consists of the following job:
# run-tests:
#    - Downloads the jaxlib and ROCm artifacts from GCS and GitHub if build_jaxlib is `false`.
#       Otherwise, the artifacts are built from source.
#    - Downloads the jax artifact from a GCS bucket if build_jax is `false`.
#       Otherwise, the artifact is built from source.
#    - If `run_multiaccelerator_tests` is `false`, executes the `run_bazel_test_rocm_rbe.sh` script,
#      which performs the following actions:
#      - `build_jaxlib=wheel`: Runs the Bazel CPU tests with py_import dependencies.
#      - `build_jaxlib=false`: Runs the Bazel CPU tests with downloaded wheel dependencies.
#      - `build_jaxlib=true`: Runs the Bazel CPU tests with individual Bazel target dependencies.
#    - If `run_multiaccelerator_tests` is `true`, executes the `run_bazel_test_rocm_non_rbe.sh`
#      script, which performs the following actions:
#      - `build_jaxlib=wheel`: Runs the Bazel CPU tests with py_import dependencies.
#      - `build_jaxlib=false`: Runs the Bazel CPU tests with downloaded wheel dependencies.

name: CI - Bazel ROCm tests

on:
  workflow_call:
    inputs:
      runner:
        description: "Which runner should the workflow run on?"
        type: string
        default: "linux-x86-64-1gpu-amd"
      python:
        description: "Which python version to test?"
        type: string
        default: "3.12"
      rocm-version:
        description: "Which ROCM version to test?"
        type: string
        default: "7"
      rocm-tag:
        description: "ROCm tag for container image (e.g., rocm720)"
        type: string
        default: "rocm720"
      enable-x64:
        description: "Should x64 mode be enabled?"
        type: string
        default: "0"
      jaxlib-version:
        description: "Which jaxlib version to test? (head/pypi_latest)"
        type: string
        default: "head"
      download-jax-from-gcs:
        description: "Whether to download the jax wheel from GCS"
        default: '1'
        type: string
      skip-download-jaxlib-and-plugins-from-gcs:
        description: "Whether to skip downloading the jaxlib and plugins from GCS (e.g for testing a jax only release)"
        default: '0'
        type: string
      gcs_download_uri:
        description: "GCS location URI from where the artifacts should be downloaded"
        default: 'gs://general-ml-ci-transient/jax-github-actions/jax/${{ github.workflow }}/${{ github.run_number }}/${{ github.run_attempt }}'
        type: string
      build_jaxlib:
        description: 'Should jaxlib be built from source?'
        required: true
        type: string
      build_jax:
        description: 'Should jax be built from source?'
        required: true
        type: string
      write_to_bazel_remote_cache:
        description: 'Whether to enable writing to the Bazel remote cache bucket'
        required: false
        default: '0'
        type: string
      run_multiaccelerator_tests:
        description: 'Whether to run multi-accelerator tests'
        required: false
        default: 'false'
        type: string
      clone_main_xla:
        description: "Should latest XLA be used?"
        type: string
        required: true
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: string
        default: 'no'
permissions: {}
jobs:
  run-tests:
    defaults:
      run:
        # Explicitly set the shell to bash
        shell: bash
    runs-on: ${{ inputs.runner }}
    container:
      image: "rocm/tensorflow-build@sha256:30e7fcfad87b74a4b916565a6156f4d8d01a2f5a4e06d0d0e6c37926a1507d72"
      volumes:
        - /data:/data
      options: >-
        --device=/dev/kfd
        --device=/dev/dri
        --security-opt seccomp=unconfined
        --group-add video
        --shm-size 64G
        --env-file /etc/podinfo/gha-gpu-isolation-settings
# Begin Presubmit Naming Check - name modification requires internal check to be updated
    name: "linux x86, jaxlib=${{ inputs.jaxlib-version }}, ROCM=${{ inputs.rocm-version }}, Python=${{ inputs.python }}, x64=${{ inputs.enable-x64 }}, build_jax=${{ inputs.build_jax }}, build_jaxlib=${{ inputs.build_jaxlib }}"
# End Presubmit Naming Check github-rocm-presubmits
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: ROCm Info
        run: |
          rocminfo
      - name: Download jaxlib wheel from PyPI
        if: inputs.build_jaxlib == 'false'
        run: |
          mkdir -p $(pwd)/dist
          python${{ inputs.python }} -m pip download jaxlib --dest $(pwd)/dist/
          echo "Downloaded wheels:" && ls -lh $(pwd)/dist/
      # Halt for testing
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@7f5ca0c263a81ed09ea276524c1b9192f1304e3c
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: "Bazel ROCm tests with build_jax=${{ inputs.build_jax }}, build_jaxlib=${{ inputs.build_jaxlib }}"
        timeout-minutes: 120
        run: |
          ./ci/run_bazel_test_rocm_rbe.sh  \
            --config=single_gpu \
            --local_test_jobs=4 \
            --//jax:build_jaxlib="${{ inputs.build_jaxlib }}" \
            --//jax:build_jax="${{ inputs.build_jax }}" \
            --repo_env=HERMETIC_PYTHON_VERSION="${{ inputs.python }}" \
            --action_env=JAX_ENABLE_X64="${{ inputs.enable-x64 }}" \
            --repo_env=TF_ROCM_RBE_DOCKER_IMAGE="rocm/tensorflow-build@sha256:30e7fcfad87b74a4b916565a6156f4d8d01a2f5a4e06d0d0e6c37926a1507d72" \
            ${JAXCI_ROCM_LOCK_FLAG:-}
      - name: Upload test artifacts
        if: always()
        continue-on-error: true
        uses: ./.github/actions/upload-test-artifacts
        with:
          artifact-name: bazel-test-artifacts-${{ inputs.runner }}-py${{ inputs.python }}-rocm${{ inputs.rocm-version }}
