name: Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  multiprocess_gpu_test:
    runs-on: ubuntu-latest  #  For self-hosted runners with GPUs, update accordingly.
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install absl-py
      - name: Run Multiprocess GPU Test
        run: |
          python -m pytest tests/multiprocess_gpu_test.py
          python -m pytests benchmarks/*.py
