# Cloud TPU CI (presubmit)

name: CI - Cloud TPU (presubmit)

on:
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'release/**'

# This should also be set to read-only in the project settings, but it's nice to
# document and enforce the permissions here.
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for main/release branches.
  cancel-in-progress: ${{ !contains(github.ref, 'release/') && github.ref != 'main' }}

jobs:
  run-bazel-test-tpu:
    if: github.event.repository.fork == false
    uses: ./.github/workflows/bazel_test_tpu.yml
    # Begin Presubmit Naming Check - name modification requires internal check to be updated
    name: "TPU test (jaxlib=head)"
    with:
      runner: "linux-x86-ct6e-180-8tpu"
      cores: "8"
      tpu-type: "v6e-8"
      python: "3.14-nogil"
      libtpu-version-type: "nightly"
      halt-for-connection: false
      build_jaxlib: "true"
      build_jax: "true"
      clone_main_xla: 1
    # End Presubmit Naming Check github-tpu-presubmits
