# Cloud TPU CI (presubmit)

name: Bazel TPU

on:
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'release/**'

# This should also be set to read-only in the project settings, but it's nice to
# document and enforce the permissions here.
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for main/release branches.
  cancel-in-progress: ${{ !contains(github.ref, 'release/') && github.ref != 'main' }}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      should-run: ${{ steps.filter.outputs.any_changed == 'true' || github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        id: filter
        if: github.event_name == 'pull_request'
        with:
          files: |
            jax/**
            jaxlib/**
            third_party/**
            BUILD
            *.bzl
            WORKSPACE*
            .github/workflows/cloud-tpu-ci-presubmit.yml
            .github/workflows/bazel_test_tpu.yml

  run-bazel-test-tpu:
    needs: check-paths
    if: github.event.repository.fork == false && github.repository_owner == 'jax-ml' && needs.check-paths.outputs.should-run == 'true'
    uses: ./.github/workflows/bazel_test_tpu.yml
    # Begin Presubmit Naming Check - name modification requires internal check to be updated
    name: "Test"
    with:
      runner: "linux-x86-ct6e-180-8tpu"
      cores: "8"
      tpu-type: "v6e-8"
      python: "3.14t"
      libtpu-version-type: "pinned"
      halt-for-connection: ${{ inputs.halt-for-connection }}
      build_jaxlib: ${{ 'true' }}
      build_jax: ${{ 'true' }}
      clone_main_xla: 0
    # End Presubmit Naming Check github-tpu-presubmits
