name: Google Chat Release Notification
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Google Chat Notification
        run: |
            curl --location --request POST '${{ secrets.RELEASES_WEBHOOK }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "text": "Release ${GITHUB_EVENT_RELEASE_NAME} at ${{github.event.release.published_at}} by ${GITHUB_EVENT_RELEASE_AUTHOR_LOGIN}. <${GITHUB_EVENT_RELEASE_URL}|[github]>"
            }'
        env:
          GITHUB_EVENT_RELEASE_NAME: ${{github.event.release.name}}
          GITHUB_EVENT_RELEASE_AUTHOR_LOGIN: ${{github.event.release.author.login}}
          GITHUB_EVENT_RELEASE_URL: ${{github.event.release.url}}
