name: Security

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for main branches.
  cancel-in-progress: ${{ github.ref != 'main' }}

defaults:
  run:
    shell: bash

jobs:
  zizmor:
    name: GitHub Actions Security Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Run zizmor
        # TODO(belitskiy): Update workflows and unpin/update zizmor version.
        run: uvx zizmor@1.24.1 --format=github .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
