name: CI - Free-threading and Thread Sanitizer (nightly)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 5 * * *"  # Daily at 05:00 UTC == 00:00 EST == 21:00 PST
  workflow_dispatch: # allows triggering the workflow run manually
  pull_request: # Automatically trigger on pull requests affecting this file
    branches:
      - main
    paths:
      - '**/workflows/tsan.yaml'
      - '**/workflows/tsan-suppressions*.txt'
permissions: {}

env:
  UV_DEFAULT_INDEX: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"
  PIP_INDEX_URL: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"

jobs:
  tsan:
    runs-on: linux-x86-n4-64
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build@sha256:ea67e8453d8b09c2ba48853da5e79efef4b65804b4a48dfae4b4da89ffd38405 # ml-build container (based on Ubuntu 22.04)
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: jax
          persist-credentials: false
      - name: Build Jax and run tests
        timeout-minutes: 180
        env:
          JAX_NUM_GENERATED_CASES: 1
          JAX_ENABLE_X64: true
          JAX_SKIP_SLOW_TESTS: true
          PY_COLORS: 1
          DEBIAN_FRONTEND: noninteractive
        run: |
          set -x
          cd jax

          echo "JAX_NUM_GENERATED_CASES=$JAX_NUM_GENERATED_CASES"
          echo "JAX_ENABLE_X64=$JAX_ENABLE_X64"
          echo "JAX_SKIP_SLOW_TESTS=$JAX_SKIP_SLOW_TESTS"

          # Build JAX and run tests
          bazel test \
              --repo_env=HERMETIC_PYTHON_VERSION=3.14-ft \
              --repo_env=HERMETIC_PYTHON_URL="https://storage.googleapis.com/ml-sysroot-testing/python/cpython-3.14.x-tsan-shared-linux-x86_64-llvm-18.1.8.tar.gz" \
              --repo_env=HERMETIC_PYTHON_SHA256=19160bafba950761dea5a3e3f831212cf6aa0d5dc8a0fb13c1caf69c009e853e \
              --repo_env=HERMETIC_PYTHON_PREFIX="cpython-3.14.x-tsan-shared-linux-x86_64-llvm-18.1.8/" \
              --verbose_failures \
              --test_env=JAX_NUM_GENERATED_CASES=$JAX_NUM_GENERATED_CASES \
              --test_env=JAX_ENABLE_X64=$JAX_ENABLE_X64 \
              --test_env=JAX_SKIP_SLOW_TESTS=$JAX_SKIP_SLOW_TESTS \
              --test_env=PYTHON_GIL=0 \
              --test_env=TSAN_OPTIONS="halt_on_error=1,suppressions=tests/config/tsan-suppressions_3.14.txt" \
              --test_env=JAX_TEST_NUM_THREADS=8 \
              --@rules_python//python/config_settings:py_freethreaded="yes" \
              --test_output=errors \
              --test_timeout=1800 \
              --config=rbe_linux_x86_64 \
              --config=tsan_shared \
              --test_tag_filters=-notsan \
              --run_under=//tests/config:oss_tsan_wrapper_sh \
              //tests:cpu_tests
