# CI - Wheel Tests (Nightly/Release) (ROCm abort only)
#
# This workflow runs only the ROCm wheel tests using the abort/retry wrapper workflow.
name: CI - Wheel Tests (Nightly/Release) (ROCm abort only)

on:
  workflow_dispatch:
    inputs:
      gcs_download_uri:
        description: "GCS location URI from where the artifacts should be downloaded"
        required: true
        default: 'gs://jax-nightly-artifacts/latest'
        type: string
      skip-download-jaxlib-and-plugins-from-gcs:
        description: "Whether to download only the jax wheel from GCS (e.g for testing a jax only release)"
        required: true
        default: '0'
        type: string
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection? (yes/no)'
        required: false
        default: 'no'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: {}

env:
  UV_DEFAULT_INDEX: "https://us-python.pkg.dev/ml-oss-artifacts-published/pypi-mirror/simple"

jobs:
  run-pytest-rocm:
    uses: ./.github/workflows/pytest_rocm_abort.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-64-1gpu-amd", "linux-x86-64-4gpu-amd", "linux-x86-64-8gpu-amd"]
          python: ["3.11", "3.12", "3.13", "3.14"]
          rocm: [
            {version: "7.2.0", tag: "rocm720"},
          ]
    name: "Pytest ROCm abort (JAX artifacts version = ${{ startsWith(github.ref_name, 'release/') && 'latest release' || 'nightly' }})"
    with:
      runner: ${{ matrix.runner }}
      python: ${{ matrix.python }}
      rocm-version: ${{ matrix.rocm.version }}
      rocm-tag: ${{ matrix.rocm.tag }}
      jaxlib-version: "head"
      skip-download-jaxlib-and-plugins-from-gcs: ${{inputs.skip-download-jaxlib-and-plugins-from-gcs}}
      gcs_download_uri: ${{inputs.gcs_download_uri}}
      halt-for-connection: ${{inputs.halt-for-connection}}
